apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-rkmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-rkmt
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-rkmt
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-rkmt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-rkmt
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/happy-path-eawk-tenant/appstudio/dc-metro-map-rkmt@sha256:3dea77da31345235f88feee3038a5501bae4d6db1b5dca80beadb81c92ec0e00
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
