apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-rkmt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/happy-path-eawk-tenant/appstudio/dc-metro-map-rkmt@sha256:3dea77da31345235f88feee3038a5501bae4d6db1b5dca80beadb81c92ec0e00
        name: my-nodejs
        resources: {}
status: {}
